---
################# delete pool configuration files
- name:  delete pool
  hosts: bitrix-hosts
  gather_facts: false
  tasks:
  - name: delete pool configuration files
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /etc/ansible/hosts
      - /etc/ansible/ansible-roles
      - /etc/ansible/host_vars
      - /etc/ansible/group_vars
      - /opt/webdir/tmp

  - name: delete pool ssh public keys
    lineinfile:
      dest: /root/.ssh/authorized_keys
      regexp: "ANSIBLE_KEY"
      state: absent

  - name: delete pool ssh private keys
    run_once: true
    delegate_to: localhost
    file:
      path: /etc/ansible/.ssh
      state: absent
