---
# stop mysql service on remote server
- include_tasks: mysql-enable_service.yml
  
- name: wait open port
  wait_for:
    port: "{{ mysql_port }}"
    delay: 10
    timeout: 100
    state: started
