---
- name: Install lsyncd
  yum:
    name: lsyncd
    state: latest
  when: inventory_hostname == cluster_web_server

- name: Create ssh-key for bitrix user
  user:
    name: bitrix
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: /home/bitrix/.ssh/id_rsa
  when: inventory_hostname == cluster_web_server

- name: Install ssh-key on tranformer node
  authorized_key:
    user: bitrix
    key: "{{ lookup('file', '/home/bitrix/.ssh/id_rsa.pub') }}"
  when: inventory_hostname == transformer_host

- name: update sysctl.conf for max_user_watches
  sysctl:
    name: fs.inotify.max_user_watches
    value: 1500000
    reload: yes
  when: inventory_hostname == cluster_web_server

- name: update sysctl.conf for max_queued_events
  sysctl:
    name: fs.inotify.max_queued_events
    value: 65536
    reload: yes
  when: inventory_hostname == cluster_web_server

- include_tasks: configs_lsyncd.yml
  vars:
    lsync_server: "{{ cluster_web_server }}"
    lsync_config: "balancer"
    lsync_started: true
    lsync_server_version: "{{ lb_distribution_version }}"
  when: inventory_hostname == transformer_host
