---
- name: configure erlang repository
  template:
    src: rabbitmq_erlang.repo.j2
    dest: /etc/yum.repos.d/rabbitmq_erlang.repo

# CentOS 7
- name: install erlang
  yum:
    name: erlang
    state: latest
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

# Rocky Linux 9 / AlmaLinux 9 / Oracle Linux 9 / CentOS Stream 9
- name: install erlang
  dnf:
    name: erlang
    state: latest
  when: (ansible_distribution == "Rocky" or ansible_distribution == "AlmaLinux" or ansible_distribution == "OracleLinux" or ansible_distribution == "CentOS") and ansible_distribution_major_version == "9"
