---
# generate site options and testing site
- include_tasks: inc_generate_site_vars.yml

# create database and user for site
- include_tasks: inc_site_mysql.yml
  when: "inventory_hostname == cluster_web_server"

# create site directories on all web servers in the pool
#
#- name: test cp1251 locale
#  shell: "locale -a | grep ru_RU.cp1251 -ic"
#  register: locale_cmd
#  ignore_errors: true
#  when: "bitrix_site_charset == 'windows-1251'"
#
#- name: ensure locale exists
#  shell: localedef -c -i ru_RU -f CP1251 ru_RU.CP1251
#  when: bitrix_site_charset == 'windows-1251' and locale_cmd.stdout == "0"
#
- include_tasks: create_basic_dirs.yml

- name: create folder for temporary files
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ site_bitrix }}"
    group: "{{ site_bitrix }}"
    mode: 0770
  loop:
    - "/home/bitrix/.bx_temp"
    - "/home/bitrix/.bx_temp/{{ web_site_db }}"
  when: "'bitrix-web' in group_names"

- name: create folder for temporary files
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0770
  loop:
    - "/etc/nginx/bx/site_settings"
    - "/etc/nginx/bx/site_settings/{{ web_site_name }}"
  when: "'bitrix-web' in group_names"

- name: create dbconn file for site
  template:
    src: dbconn.php.j2
    dest: "{{ web_site_root_dir }}/bitrix/php_interface/dbconn.php"
    owner: "{{ site_bitrix }}"
    group: "{{ site_bitrix }}"
    mode: 0660
  tags: create_site_files
  when: "'bitrix-web' in group_names"

- name: create settings file for site
  template:
    src: .settings.php.j2
    dest: "{{ web_site_root_dir }}/bitrix/.settings.php"
    owner: "{{ site_bitrix }}"
    group: "{{ site_bitrix }}"
    mode: 0660
  tags: create_site_files
  when: "'bitrix-web' in group_names"

- include_tasks: create_push_settings.yml
  when: NodeJSPush == 'enable' and inventory_hostname == cluster_web_server

- name: create upload directory
  file:
    path: "{{ web_site_root_dir }}/upload"
    owner: "{{ site_bitrix }}"
    group: "{{ site_bitrix }}"
    mode: 0770
    state: directory
  tags: create_site_files
  when: "'bitrix-web' in group_names"

# create csync configuration and sync data for site between nodes for new site
- include_tasks: create_csync2_site.yml
  when: "cluster_web_configure == 'enable' and fstype == 'csync'"

- include_tasks: configs_lsyncd_create_site.yml
  when: "cluster_web_configure == 'enable' and fstype == 'lsync'"

# cron configs
- include_tasks: create_cron_config.yml
  when: "web_site_cron == 'enable'"

# remove files
- file: 
    path: "{{ web_site_root_dir }}/bitrix/.settings.php.crm.orig"
    state: absent
  when: "'bitrix-web' in group_names"
