---
# dehydrated_type: test|prod
- name: create domains directory
  file:
    path: /home/bitrix/dehydrated/domains
    owner: bitrix
    state: directory

- name: create dehydrated config
  template: 
    src: dehydrated/config.j2
    dest: /home/bitrix/dehydrated/config
    owner: bitrix
    group: bitrix
    mode: 0640

- name: update dehydrated hook file
  copy:
    src: dehydrated/hook.sh
    dest: /home/bitrix/dehydrated/hook.sh
    owner: bitrix
    group: bitrix
    mode: 0750

- name: create dehydrated domains.txt for site
  template:
    src: dehydrated/tmp-domains.txt.j2
    dest: "/home/bitrix/dehydrated/domains/{{ site_names[0] }}.txt"

- name: get common name
  shell: "awk '{print $1}' /home/bitrix/dehydrated/domains/{{ site_names[0] }}.txt"
  register: common_name

- name: create main dehydrated domains.txt
  assemble:
    src: /home/bitrix/dehydrated/domains
    dest: /home/bitrix/dehydrated/domains.txt

- name: register dehydrated 
  shell: /home/bitrix/dehydrated/dehydrated --register --accept-terms

- name: create certificates
  shell: "/home/bitrix/dehydrated/dehydrated -c --keep-going > /home/bitrix/dehydrated_update.log 2>&1"

- name: change access rigths
  file:
    path: /home/bitrix/dehydrated
    state: directory
    owner: bitrix
    group: bitrix
    recurse: yes

- name: change access rigths
  file:
    path: /home/bitrix/dehydrated_update.log
    owner: bitrix
    group: bitrix

- name: delete old crontab strings
  lineinfile:
    dest: /etc/crontab
    regexp: "{{ item }}"
    state: absent
  with_items:
    - "/home/bitrix/dehydrated/dehydrated"
    - "/home/bitrix/dehydrated/certs"

- name: delete old line from crontab
  lineinfile:
    dest: /etc/crontab
    regexp: 'root /opt/webdir/bin/bx-dehydrated'
    state: absent

- name: update crontab
  lineinfile:
    dest: /etc/crontab
    line: "{{ 59 | random(start=0) }} {{ 9 | random(start=0) }} * * {{ 7 | random(start=4) }} root /opt/webdir/bin/bx-dehydrated"
