---
# 1. copy /etc/php.d files
# 2. remove current version php
# 3. install old version php
# 4. restart httpd

- shell: rsync -a --delete /etc/php.d/ /opt/webdir/tmp/php.d/
  args:
    creates: /opt/webdir/tmp/php.d/bitrixenv.ini

# CentOS 7
- name: enable remi php81 repository
  community.general.ini_file:
    dest: /etc/yum.repos.d/remi-php81.repo
    section: remi-php81
    option: enabled
    value: 1
  tags: remi
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: disable remi php82 repository
  community.general.ini_file:
    dest: /etc/yum.repos.d/remi-php82.repo
    section: remi-php82
    option: enabled
    value: 0
  tags: remi
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- include_tasks: reinstall_php.yml
  vars:
    is_php71: false
    is_php56: false
    is_json_module: false
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- include_tasks: php_ext_dublicates.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: convert extension names
  shell: /opt/webdir/bin/convert_phpd_files.sh
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: restart httpd
  service:
    name: httpd
    state: restarted
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

# Rocky Linux 9 / AlmaLinux 9 / Oracle Linux 9 / CentOS Stream 9
- name: backup php.ini file
  shell: /opt/webdir/bin/backup_php_ini_file.sh
  when: (ansible_distribution == "Rocky" or ansible_distribution == "AlmaLinux" or ansible_distribution == "OracleLinux" or ansible_distribution == "CentOS") and ansible_distribution_major_version == "9"

- name: enable remi php81 repository
  dnf:
    name: '@php:remi-8.1'
    state: present
  tags: remi
  when: (ansible_distribution == "Rocky" or ansible_distribution == "AlmaLinux" or ansible_distribution == "OracleLinux" or ansible_distribution == "CentOS") and ansible_distribution_major_version == "9"

- name: disable remi php82 repository
  dnf:
    name: '@php:remi-8.2'
    state: absent
  tags: remi
  when: (ansible_distribution == "Rocky" or ansible_distribution == "AlmaLinux" or ansible_distribution == "OracleLinux" or ansible_distribution == "CentOS") and ansible_distribution_major_version == "9"

- include_tasks: reinstall_php.yml
  vars:
    is_php71: false
    is_php56: false
    is_json_module: false
  when: (ansible_distribution == "Rocky" or ansible_distribution == "AlmaLinux" or ansible_distribution == "OracleLinux" or ansible_distribution == "CentOS") and ansible_distribution_major_version == "9"

- include_tasks: php_ext_dublicates.yml
  when: (ansible_distribution == "Rocky" or ansible_distribution == "AlmaLinux" or ansible_distribution == "OracleLinux" or ansible_distribution == "CentOS") and ansible_distribution_major_version == "9"

- name: convert extension names
  shell: /opt/webdir/bin/convert_phpd_files.sh
  when: (ansible_distribution == "Rocky" or ansible_distribution == "AlmaLinux" or ansible_distribution == "OracleLinux" or ansible_distribution == "CentOS") and ansible_distribution_major_version == "9"

- name: convert php.ini file
  shell: /opt/webdir/bin/convert_php_ini_file.sh
  when: (ansible_distribution == "Rocky" or ansible_distribution == "AlmaLinux" or ansible_distribution == "OracleLinux" or ansible_distribution == "CentOS") and ansible_distribution_major_version == "9"

- name: restart httpd
  service:
    name: httpd
    state: restarted
  when: (ansible_distribution == "Rocky" or ansible_distribution == "AlmaLinux" or ansible_distribution == "OracleLinux" or ansible_distribution == "CentOS") and ansible_distribution_major_version == "9"
