---
# update site config
# site_name - name of site (only site kernel or link can be used)
# option: proxy_ignore_client_abort
# value: off|on
- name: gathering facts about processed site
  delegate_to: "{{ cluster_web_server }}"
  bx_facts:
    name: list
    password: 0
    site: "{{ web_site_name }}"
    install: '(kernel|link)'
    error: 0
  tags: configure_site

- name: create variable with site options
  set_fact:
    bx_sites_info: "{{ hostvars[inventory_hostname]['bx_sites'] }}"
  tags: configure_site

- set_fact:
    string_value: "off"
  tags: configure_site

- set_fact:
    string_value: "on"
  tags: configure_site
  when: value

- name: delete option
  lineinfile:
    dest: "{{ item.NginxHTTPDir }}/{{ item.NginxHTTPConfig }}"
    owner: root
    group: root
    mode: 0664
    regexp: "{{ option }} "
    state: absent
  tags: configure_site
  with_items: "{{ bx_sites_info }}"
  when: "inventory_hostname == cluster_web_server"

- name: set option
  lineinfile:
    dest: "{{ item.NginxHTTPDir }}/{{ item.NginxHTTPConfig }}"
    owner: root
    group: root
    mode: 0664
    line: "{{ option }} {{ string_value }};"
    insertafter: "^\s*root\s+"
  when: "inventory_hostname == cluster_web_server"
  tags: configure_site
  with_items: "{{ bx_sites_info  }}"

- name: delete option
  lineinfile:
    dest: "{{ item.NginxHTTPDir }}/{{ item.NginxHTTPSConfig }}"
    owner: root
    group: root
    mode: 0664
    regexp: "{{ option }} "
    state: absent
  tags: configure_site
  with_items: "{{ bx_sites_info }}"
  when: "inventory_hostname == cluster_web_server"

- name: set option
  lineinfile:
    dest: "{{ item.NginxHTTPDir }}/{{ item.NginxHTTPSConfig }}"
    owner: root
    group: root
    mode: 0664
    line: "{{ option }} {{ string_value }};"
    insertafter: "^\s*root\s+"
  when: "inventory_hostname == cluster_web_server"
  tags: configure_site
  with_items: "{{ bx_sites_info  }}"

- name: restart nginx
  tags: configure_site
  service:
    name: nginx
    state: restarted
  when: "'bitrix-web' in group_names"
