---
# http://jabber.bx/view.php?id=89048

- name: remove crontab event
  lineinfile:
    dest: /etc/crontab
    state: absent
    regexp: "/home/bitrix/www/bitrix/modules/main/tools/cron_events.php"

- name: remove bx cront.d files
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "/etc/cron.d/bx_*"
