---
#- fail:
# upgrade php package from 81 to 82

# CentOS 7
- name: update remi-release
  yum:
    name: remi-release
    state: latest
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: disable remi php81 repository
  community.general.ini_file:
    dest: /etc/yum.repos.d/remi-php81.repo
    section: remi-php81
    option: enabled
    value: 0
  tags: remi
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: enable remi php82 repository
  community.general.ini_file:
    dest: /etc/yum.repos.d/remi-php82.repo
    section: remi-php82
    option: enabled
    value: 1
  tags: remi
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: update system by remi repository
  yum:
    name: php*
    state: latest
    update_cache: yes
    update_only: yes
  tags: php82
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- include_tasks: php_ext_dublicates.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: restart httpd
  service:
    name: httpd
    state: restarted
  tags: php82
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

# Rocky Linux 9 / AlmaLinux 9 / Oracle Linux 9 / CentOS Stream 9
- name: update remi-release
  dnf:
    name: remi-release
    state: latest
  when: (ansible_distribution == "Rocky" or ansible_distribution == "AlmaLinux" or ansible_distribution == "OracleLinux" or ansible_distribution == "CentOS") and ansible_distribution_major_version == "9"

- name: disable remi php81 repository
  dnf:
    name: '@php:remi-8.1'
    state: absent
  tags: remi
  when: (ansible_distribution == "Rocky" or ansible_distribution == "AlmaLinux" or ansible_distribution == "OracleLinux" or ansible_distribution == "CentOS") and ansible_distribution_major_version == "9"

- name: enable remi php82 repository
  dnf:
    name: '@php:remi-8.2'
    state: present
  tags: remi
  when: (ansible_distribution == "Rocky" or ansible_distribution == "AlmaLinux" or ansible_distribution == "OracleLinux" or ansible_distribution == "CentOS") and ansible_distribution_major_version == "9"

- name: update system by remi repository
  dnf:
    name: php*
    state: latest
    update_cache: yes
    update_only: yes
  tags: php82
  when: (ansible_distribution == "Rocky" or ansible_distribution == "AlmaLinux" or ansible_distribution == "OracleLinux" or ansible_distribution == "CentOS") and ansible_distribution_major_version == "9"

- name: remove php-fpm
  dnf:
    name:
    - php-fpm
    - nginx-filesystem
    state: absent
  tags: php82
  when: (ansible_distribution == "Rocky" or ansible_distribution == "AlmaLinux" or ansible_distribution == "OracleLinux" or ansible_distribution == "CentOS") and ansible_distribution_major_version == "9"

- include_tasks: php_ext_dublicates.yml
  when: (ansible_distribution == "Rocky" or ansible_distribution == "AlmaLinux" or ansible_distribution == "OracleLinux" or ansible_distribution == "CentOS") and ansible_distribution_major_version == "9"

- name: restart httpd
  service:
    name: httpd
    state: restarted
  tags: php82
  when: (ansible_distribution == "Rocky" or ansible_distribution == "AlmaLinux" or ansible_distribution == "OracleLinux" or ansible_distribution == "CentOS") and ansible_distribution_major_version == "9"
