---
# Upgrade php version
# Usage next variables
# to_php_version: 82
# php_rollback_versions - list of available version for rollback
# php_upgraded_versions - list of available version for upgrade

# upgrade

#- include_tasks: upgrade_php7.yml
#  when: to_php_version >= 70 and 70 in php_upgraded_versions
#
#- include_tasks: upgrade_php71.yml
#  when: to_php_version >= 71 and 71 in php_upgraded_versions
#
#- include_tasks: upgrade_php72.yml
#  when: to_php_version >= 72 and 72 in php_upgraded_versions
#
#- include_tasks: upgrade_php73.yml
#  when: to_php_version >= 73 and 73 in php_upgraded_versions
#
#- include_tasks: upgrade_php74.yml
#  when: to_php_version >= 74 and 74 in php_upgraded_versions
#
#- include_tasks: upgrade_php80.yml
#  when: to_php_version >= 80 and 80 in php_upgraded_versions
#
#- include_tasks: upgrade_php81.yml
#  when: to_php_version >= 81 and 81 in php_upgraded_versions

- include_tasks: upgrade_php82.yml
  when: to_php_version >= 82 and 82 in php_upgraded_versions

- include_tasks: upgrade_php83.yml
  when: to_php_version >= 83 and 83 in php_upgraded_versions

- include_tasks: upgrade_php84.yml
  when: to_php_version >= 84 and 84 in php_upgraded_versions
