---
# configure etckeeper

# CentOS 7
- name: wait for absent lockfile
  wait_for:
    state: absent
    path: /var/cache/etckeeper/packagelist.pre-install
    delay: 10
    timeout: 300
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: create lockfile
  file:
    path: /var/cache/etckeeper/packagelist.pre-install
    state: touch
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: deploy etckeeper config
  template:
    src: etckeeper.conf.j2
    dest: /etc/etckeeper/etckeeper.conf
  tags: etckeeper
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: init etckeeper
  shell: /usr/bin/etckeeper init
  args:
    creates: /etc/.hg/hgrc
  tags: etckeeper
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: check if the directory contains uncommitted changes
  shell: /usr/bin/etckeeper unclean && echo "True" || echo "False"
  register: hgstatus
  ignore_errors: True
  tags: etckeeper
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: count commit date
  shell: date +"%Y-%m-%d %H:%M:%S"
  register: commitdate
  tags: etckeeper
  #when: "'True' in hgstatus.stdout"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: commit changes by etckeeper
  shell: /usr/bin/etckeeper commit "commit from ansible task at {{ commitdate.stdout }}"
  tags: etckeeper
  #when: "'True' in hgstatus.stdout"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: delete lockfile
  file:
    path: /var/cache/etckeeper/packagelist.pre-install
    state: absent
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

# Rocky Linux 9 / AlmaLinux 9 / Oracle Linux 9 / CentOS Stream 9
- name: clear packagelist lockfile # on install will be created need delete before run something
  file:
    path: /var/cache/etckeeper/packagelist.pre-install
    state: absent
  when: (ansible_distribution == "Rocky" or ansible_distribution == "AlmaLinux" or ansible_distribution == "OracleLinux" or ansible_distribution == "CentOS") and ansible_distribution_major_version == "9"

- name: wait for absent lockfile
  wait_for:
    state: absent
    path: /var/cache/etckeeper/packagelist.pre-install
    delay: 10
    timeout: 300
  when: (ansible_distribution == "Rocky" or ansible_distribution == "AlmaLinux" or ansible_distribution == "OracleLinux" or ansible_distribution == "CentOS") and ansible_distribution_major_version == "9"

- name: create lockfile
  file:
    path: /var/cache/etckeeper/packagelist.pre-install
    state: touch
  when: (ansible_distribution == "Rocky" or ansible_distribution == "AlmaLinux" or ansible_distribution == "OracleLinux" or ansible_distribution == "CentOS") and ansible_distribution_major_version == "9"

- name: deploy etckeeper config
  template:
    src: etckeeper.conf.j2
    dest: /etc/etckeeper/etckeeper.conf
  tags: etckeeper
  when: (ansible_distribution == "Rocky" or ansible_distribution == "AlmaLinux" or ansible_distribution == "OracleLinux" or ansible_distribution == "CentOS") and ansible_distribution_major_version == "9"

- name: init etckeeper
  shell: /usr/bin/etckeeper init
  args:
    creates: /etc/.hg/hgrc
  tags: etckeeper
  when: (ansible_distribution == "Rocky" or ansible_distribution == "AlmaLinux" or ansible_distribution == "OracleLinux" or ansible_distribution == "CentOS") and ansible_distribution_major_version == "9"

- name: check if the directory contains uncommitted changes
  shell: /usr/bin/etckeeper unclean && echo "True" || echo "False"
  register: hgstatus
  ignore_errors: True
  tags: etckeeper
  when: (ansible_distribution == "Rocky" or ansible_distribution == "AlmaLinux" or ansible_distribution == "OracleLinux" or ansible_distribution == "CentOS") and ansible_distribution_major_version == "9"

- name: count commit date
  shell: date +"%Y-%m-%d %H:%M:%S"
  register: commitdate
  tags: etckeeper
  #when: "'True' in hgstatus.stdout"
  when: (ansible_distribution == "Rocky" or ansible_distribution == "AlmaLinux" or ansible_distribution == "OracleLinux" or ansible_distribution == "CentOS") and ansible_distribution_major_version == "9"

- name: commit changes by etckeeper
  shell: /usr/bin/etckeeper commit "commit from ansible task at {{ commitdate.stdout }}"
  tags: etckeeper
  #when: "'True' in hgstatus.stdout"
  when: (ansible_distribution == "Rocky" or ansible_distribution == "AlmaLinux" or ansible_distribution == "OracleLinux" or ansible_distribution == "CentOS") and ansible_distribution_major_version == "9"

- name: delete lockfile
  file:
    path: /var/cache/etckeeper/packagelist.pre-install
    state: absent
  when: (ansible_distribution == "Rocky" or ansible_distribution == "AlmaLinux" or ansible_distribution == "OracleLinux" or ansible_distribution == "CentOS") and ansible_distribution_major_version == "9"
